export const products = [
  {
    id: 1,
    nombre: "Camiseta Clásica",
    precio: 45000,
    img: "/camisetas.jpg",
    category: "Camisetas",
  },
  {
    id: 2,
    nombre: "Jean Slim Fit",
    precio: 85000,
    img: "/jeans.jpg",
    category: "Jeans",
  },
  {
    id: 3,
    nombre: "Zapatillas Urbanas",
    precio: 125000,
    img: "/zapatillas.jpg",
    category: "Zapatillas",
  },
  {
    id: 4,
    nombre: "Camiseta Estampada",
    precio: 55000,
    img: "/camiseta-estampada.jpg",
    category: "Camisetas",
  },
  {
    id: 5,
    nombre: "Jean Roto",
    precio: 95000,
    img: "/jean-roto.jpg",
    category: "Jeans",
  },
  {
    id: 6,
    nombre: "Zapatillas Deportivas",
    precio: 150000,
    img: "/zapatillas-deportivas.jpg",
    category: "Zapatillas",
  },
  {
    id: 7,
    nombre: "Camiseta Manga Larga",
    precio: 60000,
    img: "/camiseta-manga-larga.jpg",
    category: "Camisetas",
  },
  {
    id: 8,
    nombre: "Jean Clásico",
    precio: 80000,
    img: "/jean-clasico.jpg",
    category: "Jeans",
  },
  {
    id: 9,
    nombre: "Zapatillas de Lona",
    precio: 110000,
    img: "/zapatillas-lona.jpg",
    category: "Zapatillas",
  },
];